project:
  type: website
  

website:
  title: "Zhichen Xiong(Ella)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: analysis.qmd
        text: Example Analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto


